spring.application.name=pos-relational-data-service

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=controlneg_rmx_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Pruebas123*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.properties.hibernate.default_catalog=controlneg_rmx_db
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/test?retryWrites=true&loadBalanced=false&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1

# Logging configuration
logging.level.root=INFO
# Set migration import logs to DEBUG to see per-line details
logging.level.com.infinitesoft.pos_relational_data_service.services.impl.MigrationServiceImpl=DEBUG

# Task Scheduling
# Runs at 11:09 PM every day (testing purpose)
#env.task-managers.historial-total-by-date=0 9 23 * * ?
# Runs at 12:00 PM every day
env.task-managers.historial-total-by-date=0 0 12 * * ?
env.formats.date-default=yyyy-MM-dd
