spring.application.name=pos-relational-data-service

spring.datasource.url=jdbc:postgresql://localhost:5432/project_bd
spring.datasource.username=romax-admin
spring.datasource.password=f4ast3rv3rs10n*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/test?retryWrites=true&loadBalanced=false&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
